package us.inspirenc.practice.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//this comment is just a test of pushing from egit
import org.junit.Test;
import us.inspirenc.practice.*;
import static org.junit.Assert.*;
 
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
